const MILLISECONDS_IN_SECOND = 1000;
const SECONDS_IN_MINUTE = 60;
const MINUTES_IN_HOUR = 60;
const HOURS_IN_DAY = 24;
const DAYS_IN_YEAR = 365;
const MILLISECONDS_IN_YEAR = MILLISECONDS_IN_SECOND * SECONDS_IN_MINUTE * MINUTES_IN_HOUR * HOURS_IN_DAY * DAYS_IN_YEAR;

const DEFAULT_COMPROMISED_CREDENTIALS_HEADER_NAME = 'px-compromised-credentials';

const DEFAULT_ADDITIONAL_ACTIVITY_HEADER_NAME = 'px-additional-activity';
const DEFAULT_ADDITIONAL_ACTIVITY_URL_HEADER_NAME = 'px-additional-activity-url';

const DEFAULT_LOGIN_SUCCESSFUL_HEADER_NAME = 'x-px-login-successful';
const DEFAULT_LOGIN_SUCCESSFUL_HEADER_VALUE = '1';

const CSP_HEADER = 'Content-Security-Policy';
const CSPRO_HEADER = 'Content-Security-Policy-Report-Only';

const CI_USERNAME_FIELD = 'user';
const CI_PASSWORD_FIELD = 'pass';
const CI_VERSION_FIELD = 'ci_version';
const CI_RAW_USERNAME_FIELD = 'raw_username';
const CI_SSO_STEP_FIELD = 'sso_step';
const CI_CREDENTIALS_COMPROMISED_FIELD = 'credentials_compromised';

const GQL_OPERATIONS_FIELD = 'graphql_operations';
const EMAIL_ADDRESS_REGEX =
    /^([a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?)$/;
const HASH_ALGORITHM = { SHA256: 'sha256' };

const ORIGIN_HEADER = 'origin';
const ACCESS_CONTROL_REQUEST_METHOD_HEADER = 'access-control-request-method';
const TOKEN_SEPARATOR = '.';
const APP_USER_ID_FIELD_NAME = 'app_user_id';
const JWT_ADDITIONAL_FIELDS_FIELD_NAME = 'jwt_additional_fields';
const CROSS_TAB_SESSION = 'cross_tab_session';
const COOKIE_SEPARATOR = ';';

module.exports = {
    MILLISECONDS_IN_SECOND,
    SECONDS_IN_MINUTE,
    MINUTES_IN_HOUR,
    HOURS_IN_DAY,
    DAYS_IN_YEAR,
    MILLISECONDS_IN_YEAR,
    DEFAULT_COMPROMISED_CREDENTIALS_HEADER_NAME,
    DEFAULT_ADDITIONAL_ACTIVITY_HEADER_NAME,
    DEFAULT_ADDITIONAL_ACTIVITY_URL_HEADER_NAME,
    DEFAULT_LOGIN_SUCCESSFUL_HEADER_NAME,
    DEFAULT_LOGIN_SUCCESSFUL_HEADER_VALUE,
    CSP_HEADER,
    CSPRO_HEADER,
    CI_USERNAME_FIELD,
    CI_PASSWORD_FIELD,
    CI_VERSION_FIELD,
    CI_RAW_USERNAME_FIELD,
    CI_SSO_STEP_FIELD,
    CI_CREDENTIALS_COMPROMISED_FIELD,
    GQL_OPERATIONS_FIELD,
    EMAIL_ADDRESS_REGEX,
    HASH_ALGORITHM,
    ORIGIN_HEADER,
    ACCESS_CONTROL_REQUEST_METHOD_HEADER,
    TOKEN_SEPARATOR,
    APP_USER_ID_FIELD_NAME,
    JWT_ADDITIONAL_FIELDS_FIELD_NAME,
    CROSS_TAB_SESSION,
    COOKIE_SEPARATOR,
};
